### ISSUE TITLE
Use Roxygen2 for R examples

### ISSUE THREAD

**Issue by ns-rse** [Joe-Heffer-Shef/FAIR4RS-Documentation#19]
Sorry to miss the session yesterday @Joe-Heffer-Shef I had school pick-up to do bang in the middle.

I've had a look through the material though and noticed that the example of R documentation in the `introduction` episode appears to use Python style docstrings which I've never seen before and I don't know how/if they are rendered.

A common convention though is to use [roxygen2](https://roxygen2.r-lib.org/index.html) for documenting functions (its described in the [R Packages (2e) : Function Documentation](https://r-pkgs.org/man.html).

I thought it would be useful use this convention and reference Roxygen2 rather than people learn one way of doing things and then have to re-learn another method.

EDIT : I've found that this is referenced further in the material under Code Readability.

**Comment by Joe-Heffer-Shef** [comment]
Thanks Neil,
roxygen formatting is now used in the docstring episode
https://joe-heffer-shef.github.io/FAIR4RS-Documentation/docstrings.html
