### ISSUE TITLE
Include Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by ns-rse** [Joe-Heffer-Shef/FAIR4RS-Documentation#21]
To supplement the `contributors` episode it might be worth considering including reference to a Code of Conduct as well as Contributing guidelines so that people learn to include not just technical details of how to contribute but to include details of the expected behaviour of contributors.

One resource I've seen used for this in the past are the [Contributor Covenant: Code of Conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/).

**Comment by Joe-Heffer-Shef** [comment]
I've added a section on Code of Conduct in PR https://github.com/Joe-Heffer-Shef/FAIR4RS-Documentation/pull/31

I'd intentionally excluded talking about project governance/management which I might be covered in section 1a (software management planning)
