### ISSUE TITLE
Code readability R without syntax highlighting not rendered correctly

### ISSUE THREAD

**Issue by ns-rse** [Joe-Heffer-Shef/FAIR4RS-Documentation#23]
The first code box on the R tab of the [Code Readability Episode](https://joe-heffer-shef.github.io/FAIR4RS-Documentation/readable.html) where R code is meant to be shown without syntax highlighting renders with syntax highlighting.

Not sure why this might be as the language is denoted as `output` in the Markdown file. :thinking:

**Comment by Joe-Heffer-Shef** [comment]
I noticed this. I found this list of all the supported languages so I picked `default` which seems to fix it.

https://github.com/jgm/skylighting/tree/master/skylighting-core/xml

(source: https://carpentries.github.io/sandpaper-docs/aio.html#code-blocks-with-syntax-highlighting)
